# Numpy


In [1]:
def print_name():
    print("4SF20CI002 - ABHIJITH MALLYA")


#####  Creating Numpy Array

In [23]:
import numpy as np
a = np.array(([1,2,3,4,5],[6,7,8,9,10]))
print_name()
print(a)

4SF20CI002 - ABHIJITH MALLYA
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


####  Array dimentions

In [36]:
print_name()
print("Shape : "+str(a.shape))
print("Length :"+str(len(a)))
print("Datatype :"+str(a.dtype))

4SF20CI002 - ABHIJITH MALLYA
Shape : (2, 5)
Length :2
Datatype :int32


#### Reshaping the array


In [37]:
print_name()
a.reshape(5,2)

4SF20CI002 - ABHIJITH MALLYA


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

#### Accessing elements in an array

In [48]:
print_name()
print(a[0][1])
print(a[1][4])
print(a[0][3])




4SF20CI002 - ABHIJITH MALLYA
2
10
4


#### Min and Max of array


In [50]:
print_name()
print("Minimum : "+str(np.min(a)))
print("Maximum : "+str(np.max(a)))

4SF20CI002 - ABHIJITH MALLYA
Minimum : 1
Maximum : 10


#### Calculating Mean of array

In [53]:
print_name()
print("Mean : "+str(np.mean(a)))

4SF20CI002 - ABHIJITH MALLYA
Mean : 5.5


#### Sum of all elements


In [69]:
print_name()
print("Sum : "+str(np.mean(a)))

4SF20CI002 - ABHIJITH MALLYA
Sum : 5.5


#### Sqrt and Exponents


In [70]:
print_name()
b=np.array([144,169,25,100])
print("Square Root : "+str(np.sqrt(b).astype(int)))
print("Exponent : "+str(np.exp(b)))


4SF20CI002 - ABHIJITH MALLYA
Square Root : [12 13  5 10]
Exponent : [3.45466066e+62 2.48752493e+73 7.20048993e+10 2.68811714e+43]


#### Addition of Arrays

In [71]:
print_name()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_sum = arr1 + arr2
print(arr_sum)

4SF20CI002 - ABHIJITH MALLYA
[5 7 9]


#### Multiplication of Arrays

In [72]:
print_name()
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.matmul(matrix1, matrix2)
print(matrix_product)

4SF20CI002 - ABHIJITH MALLYA
[[19 22]
 [43 50]]
